[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["kobina <maadabrandon@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
geopy = "^2.4.1"
tqdm = "^4.66.1"
pyarrow = "^14.0.2"
jupyter = "^1.0.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
